jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "chocolateen"
          password: ${USER_CHOCOLATEEN_PASSWORD}
          name: "Hugo"
        - id: "vaugie_g"
          password: ${USER_VAUGIE_G_PASSWORD}
          name: "Garance"
        - id: "i_dont_know"
          password: ${USER_I_DONT_KNOW_PASSWORD}
          name: "Jeremy"
        - id: "nasso"
          password: ${USER_NASSO_PASSWORD}
          name: "Nassim"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            entries:
              - user: "chocolateen"
          - name: "ape"
            description: "Pedagogical team members"
            permissions:
              - "Overall/Read"
              - "Job/Build"
            entries:
              - user: "i_dont_know"
          - name: "gorilla"
            description: "1111"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Create"
              - "Job/Configure"
              - "Job/Delete"
              - "Job/Move"
              - "Job/Cancel"
            entries:
              - user: "vaugie_g"
          - name: "assist"
            description: "Assistant"
            permissions:
              - "Overall/Read"
              - "Job/Read"
            entries:
              - user: "nasso"            
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "noHostKeyVerificationStrategy"
    # globalHostKeyVerificationConfiguration:
    # sshHostKeyVerificationStrategy:
    #   manuallyProvidedKeyVerificationStrategy:
    #     approvedHostKeys: |
    #       github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
    #       github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7OPK74CBZYjeCR5GAXYiW8ggRgiDhkwQQmrXRE3BtIL3jGryntc7gEXW76w8m9ZsN74U=
    #       github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLCS1cXODkyRF8GCEB9JyjOCu5bhFux5DGln03XZ2IQkbY39YKt6VtbM8mE6W6XqBpIbtYylUtMabUEmL89hth6vHGDThjbUGfGgbHJxtwBmEMwHIE2g3q9nj7b+1ahXYOMGiSM0rS9b++WORf+eH7kG6gH7sFQtZPE89XWTA6Ib3E8m8t8crRmWIn9YfA7AgJaW2asNWDxtvHLNfD2C6SvejaIFOPjc3mNTo8tubImToisX73llR87SBdhLAvSBymLglCX5B6CXSuYyCrkbCH5nHyXptUnO+VIvSjrmXy7A7YHJGo8MHXYRNjHCH8vH270EZF8M8A2N3LLol8WZxlO7wBffwA9S43fUUs85EwOIyY16HeK4E449m2159iG3Ue0O1w0G2dJj40989=
credentials:
    system:
      domainCredentials:
      - credentials:
        - basicSSHUserPrivateKey:
            id: "admin-ssh-key"
            privateKeySource:
              directEntry:
                privateKey: ${SSH_PRIVATE_KEY}
            scope: GLOBAL
            username: "admin"
jobs:
  - file: /var/jenkins_casc_configs/job_dsl.groovy

      